pipeline {
     agent any

     options {
          skipStagesAfterUnstable()
          skipDefaultCheckout(true)
     }

     environment {
        GRADLEW = './CA2/Part2/gradle-migration/gradlew -p CA2/Part2/gradle-migration'
     }

     stages {
        stage('Repository Checkout') {
               steps {
                    echo 'Repository Checkout'
                    checkout scm
               }
        }

        stage('Build Step') {
               steps {
                    echo 'Generating deployment file'
                    echo "Running Build ${env.BUILD_ID}"

                    script {
                        if (isUnix()) {
                              sh '${GRADLEW} clean build'
                        } else {
                              bat '${GRADLEW} clean build'
                        }
                    }

                    archiveArtifacts artifacts: 'build/libs/*.jar'
               }
        }

        stage('Unit Tests') {
               steps {
                    echo 'Unit Tests'

                    script {
                         if (isUnix()) {
                              sh '${GRADLEW} test'
                    } else {
                              bat '${GRADLEW} test'
                         }
                    }
               }
        }

     }
}