# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  # Global update for all VMs
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y git

    # Clone project
    cd /home/vagrant/
    git clone https://github.com/1211711/cogsi2526-1211711-1210631.git
    cd cogsi2526-11211711-11210631
    git checkout feature/issue-19/setup_multiple_virtual_machines

    echo "Global provisioning complete!"
  SHELL

  config.vm.define "db" do |db|
    db.vm.hostname = "db-server"

    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get install -y openjdk-17-jdk

      echo "DB provisioning complete!"
    SHELL
  end

  config.vm.define "web" do |web|
    web.vm.hostname = "web-server"

    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get install -y openjdk-17-jdk

      echo "Web provisioning complete!"
    SHELL
  end

end
